# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Python dependencies via pip/uv
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "niksacdev"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      development:
        patterns:
          - "pytest*"
          - "mypy*"
          - "ruff*"
          - "black*"
          - "pre-commit*"
      openai:
        patterns:
          - "openai*"
          - "agents*"
      documentation:
        patterns:
          - "mkdocs*"
          - "sphinx*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 3
    reviewers:
      - "niksacdev"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"