# Pre-commit hooks for security and code quality
# Install: pip install pre-commit && pre-commit install

repos:
  # Security - Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*\.lock|package-lock\.json

  # Python code quality
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  # Check for common issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  # Markdown formatting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--fix']

  # Security - Safety check
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check

# Additional local hooks
- repo: local
  hooks:
    - id: no-env-files
      name: Block .env files
      entry: .env files must not be committed
      language: fail
      files: '^\.env$'
    
    - id: no-api-keys
      name: Check for API keys
      entry: 'sk-[a-zA-Z0-9]{48}|AKIA[0-9A-Z]{16}'
      language: pygrep
      types: [text]
      exclude: \.env\.example|SECURITY\.md