# Sequential Loan Processing Pattern
# Agents process loan applications in sequence, with each agent building on the previous results

name: "sequential_loan_processing"
description: "Standard sequential processing for comprehensive loan evaluation"
pattern_type: "sequential"
version: "1.0.0"

# Agent execution order and configuration
agents:
  - type: "intake"
    name: "Application Intake"
    required: true
    timeout_seconds: 30
    description: "Fast data completeness check and routing assignment"
    success_conditions: []
    
  - type: "credit" 
    name: "Credit Assessment"
    required: true
    timeout_seconds: 240
    depends_on: ["intake"]
    description: "Evaluates creditworthiness and calculates risk metrics"
    success_conditions: []
    
  - type: "income"
    name: "Income Verification"
    required: true  
    timeout_seconds: 240
    depends_on: ["credit"]
    description: "Verifies employment and income stability"
    success_conditions: []
    
  - type: "risk"
    name: "Risk Evaluation"
    required: true
    timeout_seconds: 300
    depends_on: ["income"]
    description: "Synthesizes all assessments and provides final recommendation"
    success_conditions: []

# Handoff rules between agents
handoff_rules:
  - from: "intake"
    to: "credit"
    conditions: []
    context_fields:
      - "validation_status"
      - "data_completeness_score"
      - "fraud_indicators" 
      - "verification_results"
      - "processing_path"
    failure_action: "manual_review"
    
  - from: "credit"
    to: "income"
    conditions: []
    context_fields:
      - "credit_score"
      - "credit_tier"
      - "debt_to_income_ratio"
      - "risk_category"
      - "red_flags"
    failure_action: "conditional_review"
    
  - from: "income" 
    to: "risk"
    conditions: []
    context_fields:
      - "verified_monthly_income"
      - "employment_stability_score"
      - "income_trend"
      - "qualifying_income"
      - "concerns"
    failure_action: "income_verification_required"

# Simplified decision matrix focused on showcasing agent pattern
decision_matrix:
  auto_approve:
    description: "Automatic approval for strong applications"
    conditions:
      - "risk_recommendation == 'APPROVE'"
    max_amount: 500000
    rate_adjustment: 0.0
    
  conditional_approval:
    description: "Approval with conditions for moderate applications"
    conditions:
      - "risk_recommendation == 'CONDITIONAL_APPROVAL'"
    max_amount: 400000
    rate_adjustment: 0.25
    required_conditions:
      - "Additional documentation as specified by agents"
      
  manual_review:
    description: "Requires human review as recommended by risk agent"
    conditions:
      - "risk_recommendation == 'MANUAL_REVIEW'"
    escalation_priority: "standard"
    
  auto_deny:
    description: "Applications that do not meet basic requirements"
    conditions:
      - "risk_recommendation == 'DENY'"
    denial_reason_required: true

# Error handling configuration  
error_handling:
  agent_timeout:
    action: "retry_once"
    max_retries: 1
    fallback: "manual_review"
    
  agent_failure:
    action: "escalate"
    fallback: "manual_review"
    
  invalid_output:
    action: "retry_with_clarification"
    max_retries: 2
    fallback: "manual_review"

# Monitoring and audit configuration
monitoring:
  track_metrics:
    - "processing_duration_by_agent"
    - "success_rate_by_agent"
    - "handoff_failure_rate"
    - "decision_distribution"
    
  audit_points:
    - "agent_handoffs"
    - "decision_factors"
    - "compliance_checks"
    - "error_occurrences"

# Compliance requirements
compliance:
  required_verifications:
    - "identity_verification"
    - "income_verification" 
    - "credit_verification"
    
  audit_trail_required: true
  decision_reasoning_required: true
  regulatory_flags:
    - "HMDA_reporting"
    - "fair_lending_compliance" 
    - "ATR_QM_compliance"